name: Jimmyboy
favicon: null
layout_spectrum: 0.20197013625875115
typography_spectrum: 0.5842107199132442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.14547302736900747
  lightness: 0.8412329342681915
  saturation: 0.45838294620625675
  rhythmicContrast: 0.7150743259117007
purpose: []
